apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssp-idp
  name: ssp-idp
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 80
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    app: ssp-idp
